name: React CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  test-react-app:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Download Code from GitHub
        uses: actions/checkout@v4

      - name: 2. Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Install React Dependencies
        run: npm install

      - name: 4. Check if the App Builds Successfully
        run: npm run build

      - name: 5. Save the Build (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: react-production-build
          path: dist/

  deploy-dev:
    needs: test-react-app
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-production-build
          path: dist/
      - run: echo "🚀 Deploying to DEV Server..."

  deploy-staging:
    needs: deploy-dev
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-production-build
          path: dist/
      - run: echo "🧪 Deploying to STAGING Server..."

  deploy-prod:
    needs: deploy-staging
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-production-build
          path: dist/
      - run: |
          echo "🌐 Deploying to PRODUCTION Server..."
          echo "Using Prod Secret: ${{ secrets.MY_API_KEY }}"



 
    
